// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoesHouse.Data.EF;

namespace ShoesHouse.Data.Migrations
{
    [DbContext(typeof(ShoesHouseDbContext))]
    [Migration("20220127155112_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AppUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("372ea575-2536-4076-9bab-3e3138de495f"),
                            RoleId = new Guid("9e87b492-5343-4272-9a34-fa5de7cffb22")
                        },
                        new
                        {
                            UserId = new Guid("8a820adb-93d7-4c6f-9404-bdbfc14419f4"),
                            RoleId = new Guid("8f7579ee-4af9-4b71-9ada-7f792f76dc31")
                        },
                        new
                        {
                            UserId = new Guid("51b4b238-4ae0-4e46-a3f4-e0acf7666b15"),
                            RoleId = new Guid("8f7579ee-4af9-4b71-9ada-7f792f76dc31")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("AppUserTokens");
                });

            modelBuilder.Entity("ShoesHouse.Data.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppRole");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9e87b492-5343-4272-9a34-fa5de7cffb22"),
                            ConcurrencyStamp = "8435f3fa-828b-4b0a-aa81-0a2084343fac",
                            Description = "Administrator role",
                            Name = "admin",
                            NormalizedName = "admin"
                        },
                        new
                        {
                            Id = new Guid("8f7579ee-4af9-4b71-9ada-7f792f76dc31"),
                            ConcurrencyStamp = "1beaf212-511e-4289-8f7f-eb23e7b4f040",
                            Description = "Customer role",
                            Name = "customer",
                            NormalizedName = "customer"
                        });
                });

            modelBuilder.Entity("ShoesHouse.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("Avatar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("default-avatar.png");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(225)
                        .HasColumnType("nvarchar(225)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUser");

                    b.HasData(
                        new
                        {
                            Id = new Guid("372ea575-2536-4076-9bab-3e3138de495f"),
                            AccessFailedCount = 0,
                            Address = "Can Tho",
                            ConcurrencyStamp = "c1092afc-f17c-4d88-8c0f-d958f20d2591",
                            DoB = new DateTime(2000, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "huy@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Lam Nhut Huy",
                            NormalizedEmail = "huy@gmail.com",
                            NormalizedUserName = "admin",
                            PasswordHash = "AQAAAAEAACcQAAAAECxAACcJV8b2uDTkgHoatkfHXQxtKhngmb2rJrj1RNZUfS9ySa+oiVqbqohqizG1zg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("8a820adb-93d7-4c6f-9404-bdbfc14419f4"),
                            AccessFailedCount = 0,
                            Address = "131, phường Cầu Kho, quận 1, TP.HCM",
                            ConcurrencyStamp = "d5f403c5-fe3d-421a-b63d-845b7c3ea6bc",
                            DoB = new DateTime(1999, 9, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hoang@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Nguyen Van Hoang",
                            NormalizedEmail = "hoang@gmail.com",
                            NormalizedUserName = "user",
                            PasswordHash = "AQAAAAEAACcQAAAAELQ7w0Hdo322ETn48mwOKgQNPR03mIixIoNbbzxR7hdyozVs+CisUrxcBydryIKOQw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "nguyenvanhoang"
                        },
                        new
                        {
                            Id = new Guid("51b4b238-4ae0-4e46-a3f4-e0acf7666b15"),
                            AccessFailedCount = 0,
                            Address = "Kiên Giang",
                            ConcurrencyStamp = "bd77fc9a-b6d5-444e-b19f-b8e30ebde25e",
                            DoB = new DateTime(2001, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "duyen@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Tran Thi My Duyen",
                            NormalizedEmail = "duyen@gmail.com",
                            NormalizedUserName = "user",
                            PasswordHash = "AQAAAAEAACcQAAAAEMDniwr2grAmabD2xpYDQ1NH7T+b/b3EkMyfNQggH/gpdfK8hTVTLfJxzrBGO7qIqw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "myduyentran"
                        });
                });

            modelBuilder.Entity("ShoesHouse.Data.Entities.Cart", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("UserId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("ShoesHouse.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "All the must-have releases from Nike, with everything from icons like the Nike Air Force 1 and Nike Air Max line, to Nike SB, to the latest in-demand collaborations from the famous footwear brand known and loved across the globe.",
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The \"Brand with the 3 Stripes\" is a legend, birthing classics from the Stan Smith to the Superstar before reinventing itself with NMD, Ultra Boost, and its Yeezy collection.",
                            Name = "Adidas"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Known for premium quality and ultimate comfort, New Balance is one of the world’s premier athletic footwear brands. Find a full range of the New England-based brand’s retro runners, modern hits, and coveted collaborations here.",
                            Name = "New Balance"
                        },
                        new
                        {
                            Id = 4,
                            Description = "More than a century of established excellence.",
                            Name = "Converse"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Live \"Off The Wall\" with Vans Old Skools, Vans Slip-Ons, and more.",
                            Name = "Vans"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Retro classics like the Gel-Lyte III and much more.",
                            Name = "Asics"
                        });
                });

            modelBuilder.Entity("ShoesHouse.Data.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 851, DateTimeKind.Local).AddTicks(420),
                            ProductId = 1,
                            UserId = new Guid("8a820adb-93d7-4c6f-9404-bdbfc14419f4"),
                            content = "Giày đẹp"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 851, DateTimeKind.Local).AddTicks(672),
                            ProductId = 2,
                            UserId = new Guid("8a820adb-93d7-4c6f-9404-bdbfc14419f4"),
                            content = "Giày mang hơi rộng."
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 851, DateTimeKind.Local).AddTicks(676),
                            ProductId = 1,
                            UserId = new Guid("51b4b238-4ae0-4e46-a3f4-e0acf7666b15"),
                            content = "Giày mang êm"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 851, DateTimeKind.Local).AddTicks(678),
                            ProductId = 2,
                            UserId = new Guid("51b4b238-4ae0-4e46-a3f4-e0acf7666b15"),
                            content = "Giao hàng hơi chậm"
                        });
                });

            modelBuilder.Entity("ShoesHouse.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeliveryDate = new DateTime(2022, 1, 30, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            Total = 2200000m,
                            UserId = new Guid("8a820adb-93d7-4c6f-9404-bdbfc14419f4")
                        },
                        new
                        {
                            Id = 2,
                            DeliveryDate = new DateTime(2022, 2, 5, 10, 25, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            Total = 5000000m,
                            UserId = new Guid("8a820adb-93d7-4c6f-9404-bdbfc14419f4")
                        },
                        new
                        {
                            Id = 3,
                            DeliveryDate = new DateTime(2022, 2, 1, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Status = 4,
                            Total = 1600000m,
                            UserId = new Guid("51b4b238-4ae0-4e46-a3f4-e0acf7666b15")
                        },
                        new
                        {
                            Id = 4,
                            DeliveryDate = new DateTime(2022, 2, 6, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Total = 1700000m,
                            UserId = new Guid("51b4b238-4ae0-4e46-a3f4-e0acf7666b15")
                        });
                });

            modelBuilder.Entity("ShoesHouse.Data.Entities.OrderDetail", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            ProductId = 16,
                            Amount = 1
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = 1,
                            Amount = 1
                        },
                        new
                        {
                            OrderId = 3,
                            ProductId = 12,
                            Amount = 1
                        },
                        new
                        {
                            OrderId = 2,
                            ProductId = 5,
                            Amount = 1
                        },
                        new
                        {
                            OrderId = 4,
                            ProductId = 8,
                            Amount = 1
                        });
                });

            modelBuilder.Entity("ShoesHouse.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 827, DateTimeKind.Local).AddTicks(680),
                            Description = "The Nike Dunk High “Dark Curry” puts an appealing lifestyle look on the timeless high-top shoe. The “Dark Curry” was released in March 2021 and exemplifies Nike’s efforts of expanding the Dunk’s footprint in sneakers. A year earlier, in 2020, the Nike Dunk re-emerged from relative obscurity to once again capture the attention of sneaker collectors due to an impressive amount of limited edition collaborations and returning retro colorways.As for the design of the “Dark Curry,” hairy orange-brown suede overlays on the model’s forefoot, eyelets, collar, and heel contrast the black brushed suede base. A darker shade of brown suede can be found on the Swoosh branding on either side and on the small pull tab on the heel. Nike layers brown laces over the black mesh tongue and adds a midsole for a timeless look. Underfoot, a tan outsole finishes off the look of the “Dark Curry.” ",
                            Name = "Nike Dunk High “Dark Curry” ",
                            OriginalPrice = 2500000m,
                            Size = 42,
                            Stock = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(2676),
                            Description = "The BBC x Pharrell x adidas NMD Hu “Astronaut Blue” is a November 2021 collaboration between the Virginia native, his streetwear brand, and adidas on the former’s popular signature shoe. This three-way collaboration between Billionaire Boys Club, Pharrell, and adidas brings a neutral-colored look to the NMD Hu. The “Astronaut Blue” features BBC’s signature “Astronaut” branding on its design, specifically on the top of both the left and right shoe. The upper is constructed from a Halo Blue-colored sweater-like material, the same ribbed knit upper that is also found on the adidas NMD Hu’s “Cream” colorway. The shoe is constructed in a slip-on-like style with wraparound laces incorporated into the translucent midfoot cage found on either side. BBC’s “Astronaut” logo appears on the back of the left shoe while adidas’s Trefoil logo is found on the back of the right shoe. Underfoot, a responsive Boost midsole completes the look.",
                            Name = "Pharrell - Billionaire Boys Club - Astronaut Blue ",
                            OriginalPrice = 2100000m,
                            Size = 41,
                            Stock = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(2700),
                            Description = "The Salehe Bembury x New Balance 2002R is the second highly coveted collaboration by the footwear and fashion designer and New Balance. As its nickname implies, the colorway is inspired by water, the source of life for us all, and is colored accordingly with a refreshing aqua blue hairy suede upper. Premium brown leather detailing is found on the tongue and at the ankle, while the light tan mesh base adds plenty of breathability. Shearling N logos in green add another earthy vibe. New Balance's NERGY foam midsole provides a light and cushioned feel all day long",
                            Name = "Salehe Bembury - Water Be The Guide",
                            OriginalPrice = 2400000m,
                            Size = 42,
                            Stock = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(2703),
                            Description = "The Converse Run Star Hike Hi gives the classic Chuck Taylor design an edgy twist with its chunky platform style and jagged sole. The upper remains untouched from its original style with the black canvas construction, white rubber toe cap, and Chuck Taylor emblem. Meanwhile, the bottom introduces a new look with a two-tone outsole and thick platform that remains true to its iconic roots. This iteration lends a fashion-forward appeal and modern vibe.",
                            Name = "Run Star Hike",
                            OriginalPrice = 1300000m,
                            Size = 42,
                            Stock = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(2706),
                            Description = "The Notre x Vans OG Old Skool LX \"White\" is one of several colorways of the classic lifestyle shoe created by the Chicago clothing and sneaker boutique and Vans for Fall 2020. The Vans OG Old Skool LX receives several updates in design from its venerable Old Skool relative, including a new premium suede construction, a padded leather collar, and cream, vulcanized midsole. Here, on the Notre-designed “White” colorway, hairy cream suede can be found on the entire upper. Notre places its signature handshake logo on either side in place of the Old Skool’s signature wavy detailing. A black “Vans” branded license plate resides on the heel of the cream sole",
                            Name = "Vans attitude Notre - White",
                            OriginalPrice = 1600000m,
                            Size = 42,
                            Stock = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 6,
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(2708),
                            Description = "The Concepts x ASICS GEL-Lyte III \"Otoro\" is a collaborative sneaker that exemplifies storytelling at its finest. Symbolic of the Bluefin Tuna and its highly acclaimed belly fat called “Otoro,” this special-edition shoe updates the Gel-Lyte III silhouette with premium pigskin suede in various shades of pink—which is a nod to the beautiful color of the fish. Reflective accents represent sushi tools used to eat the delectable dish. To commemorate the collaboration, a Concepts logo is debossed into the lateral heel area",
                            Name = " Asics Concepts - Otoro",
                            OriginalPrice = 2000000m,
                            Size = 42,
                            Stock = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 6,
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(2710),
                            Description = "These Asics Gel Excite 7 Men's Running Shoes have been crafted with an AmpliFoam midsole which delivers a flexible and tactile ride as well as offering exceptional cushioning with every stride. The breathable mesh fabric upper allows your feet to remain cool and comfortable throughout your run, whilst the GEL technology helps absorb shock and adds further cushioning for a comfortable running experience.",
                            Name = "Asics Gel Excite 7 Men's Running",
                            OriginalPrice = 1900000m,
                            Size = 42,
                            Stock = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(2712),
                            Description = "Palladium Pampa Lite Overlab Neon for active and on-the-go young people, made from a combination of two high-quality waterproof polyester and ballistic mesh fabrics. In addition, it comes with an outsole that uses advanced Lite - Tech technology to help reduce the weight of the shoes significantly. Vibrant neon colors along with brand details give the design a striking trendy look, with a trendy look and setting it apart from the crowd.",
                            Name = "Palladium Pampa Lite Overlab Neon",
                            OriginalPrice = 1700000m,
                            Size = 42,
                            Stock = 0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(2714),
                            Description = "White leather/rubber Air Force 1 '07 Craft sneakers from NIKE featuring round toe, flat rubber sole, front lace - up fastening, branded insole, signature Swoosh logo detail and perforated design.These styles are supplied by a premium sneaker marketplace.Stocking only the most sought - after footwear, they source and curate some of the most hard to find sneakers from around the world",
                            Name = "Nike Air Max 98 South Beach",
                            OriginalPrice = 1750000m,
                            Size = 42,
                            Stock = 0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(2716),
                            Description = "The Joe Freshgoods x New Balance 990V3 “Outside Clothes” is the much anticipated follow up to the Chicago native’s heralded collaboration with the Boston footwear company on the 992 “No Emotions Are Emotions” from 2020. The “Outside Clothes” colorway of the classic 990V3 was released in limited quantities exclusively in Joe Freshgoods’ hometown of Chicago at Garfield Park where he grew up. Accompanied by an advertisement directed by Mike Carson and scored by Alchemist that explains the origins of the design, the multicolor look features beige suede overlays atop an aqua mesh base. A light blue “N” logo appears on both sides of the shoe. Neon green “JFG” branding is printed on the lateral side of the heel and “Outside” and “Clothes” are embroidered in green script on the left and right shoe, respectively. The phrase “Made for Us” appears on the heel. Together, the colors on the shoe: green, brown, and blue, represent grass, dirt, and the sky—all elements of being outside on a warm summer’s day",
                            Name = "Joe Freshgoods x New Balance 990V3 Outside Clothes",
                            OriginalPrice = 2400000m,
                            Size = 42,
                            Stock = 0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(2718),
                            Description = "Creating a pleasant feeling at first sight, Vans Classic Sport Era owns an extremely delicate color scheme, alternating between two gentle but equally youthful Drizzle & Ballad Blue colors to create a trendy look. personalities. The dynamic, flexible Era design is made entirely of high-quality, smooth and soft Textile fabric that promises to bring you the best wearing experience.",
                            Name = "Vans UA Era Classic Sport",
                            OriginalPrice = 2210000m,
                            Size = 42,
                            Stock = 0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(2720),
                            Description = "The Sean Wotherspoon x adidas Superstar “SuperEarth - Black” is the follow-up release of the debut collaboration between the vintage apparel and footwear curator and adidas. Wotherspoon and adidas’s first “SuperEarth” collaboration took place in August 2010 with this “Black” colorway releasing in October 2021. Consistent with the theme of all of Wotherspoon’s sneaker collaborations, the Superstar SuperEarth is an all-vegan shoe made from recycled materials. The upper features a multicolor embroidered floral motif across either side. Metallic Gold “SuperEarth” and “adidas” branding are printed on the left and right light blue leather heel tabs, respectively. The cream rubber shell toe brings a classic Superstar look onto this modern colorway. Mismatched leather eyelet panels combine with unique “SuperEarth” inspired branding on the left and right tongue tags to form a progressive look",
                            Name = "Superturf Adventure SW x A GW8810",
                            OriginalPrice = 2500000m,
                            Size = 42,
                            Stock = 0
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(2722),
                            Description = "Chuck Taylor All Star II Festival with soft, high-elastic Knit knit fabric is the ideal choice for women who like to exercise. The design of the shoe body with eye-catching patterns creates a prominent highlight for the product line. Soft Lunarlon shoe insole provides comfort as well as safety for the wearer despite long-time operation.",
                            Name = "Converse Chuck 70 Fuzzy Ambush ",
                            OriginalPrice = 1950000m,
                            Size = 42,
                            Stock = 0
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 1,
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(2724),
                            Description = "The Fragment x Sacai x Nike LDWaffle “Blackened Blue” is a yet another chapter in the three-way collaboration between Hiroshi Fujiwara and Chitose Abe’s clothing brands and Nike on the hybrid shoe. The “Blackened Blue” is one of multiple colorways of the fusion shoe that combines elements of the Nike LDV and Waffle Racer released by Fragment, Sacai, and Nike in 2021. Black mesh can be found on the base while Blue Void hairy suede appears on the overlays on the forefoot, eyelets, and heel. Two white leather Swooshes are layered over one another on either side. Dual Sacai and Nike branding is printed on the white leather heel tab. Two sets of navy blue laces are placed on top of the stacked tongues. The aforementioned design elements are taken from the original Sacai x Nike LDWaffle. Text reading “The Classic / Fragment : sacai” is printed on the white foam midsole",
                            Name = "Fragment x Sacai x Nike LDWaffle Blackened Blue",
                            OriginalPrice = 2110000m,
                            Size = 42,
                            Stock = 0
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 6,
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(2726),
                            Description = "Asics Lite Overlab Neon is for active and on-the-go young people, made from a combination of two high-quality waterproof polyester and ballistic mesh fabrics. In addition, it comes with an outsole that uses advanced Lite - Tech technology to help reduce the weight of the shoes significantly. Vibrant neon colors along with brand details give the design a striking trendy look, with a trendy look and set apart from the crowd.",
                            Name = "HS1 S Tarther Blast 1201A190 300",
                            OriginalPrice = 2350000m,
                            Size = 40,
                            Stock = 0
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(2728),
                            Description = "The HUMAN MADE x adidas Originals Tokio Solar HM adds vibrant green color to a new silhouette brought to you by visionary creative and archivist NIGO. The collaborative adidas shoe draws inspiration from NIGO’s personal archive and adidas’s vintage sporting heritage. Taking design elements from the Tokio trainer that was developed for the 1964 Tokyo Olympics, the Tokio Solar HM is made of a Primeknit upper with suede panels and leather Three Stripes. An 'X' detail, made out of the same leather as the Three Stripes, appears on the mid panel and heel.",
                            Name = "Adidas Originals Tokio Solar HM",
                            OriginalPrice = 2200000m,
                            Size = 41,
                            Stock = 0
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(2729),
                            Description = "The Sean Wotherspoon x adidas Superstar “SuperEarth - Black” is the follow-up release of the debut collaboration between the vintage apparel and footwear curator and adidas. Wotherspoon and adidas’s first “SuperEarth” collaboration took place in August 2010 with this “Black” colorway releasing in October 2021. Consistent with the theme of all of Wotherspoon’s sneaker collaborations, the Superstar SuperEarth is an all-vegan shoe made from recycled materials. The upper features a multicolor embroidered floral motif across either side. Metallic Gold “SuperEarth” and “adidas” branding are printed on the left and right light blue leather heel tabs, respectively. The cream rubber shell toe brings a classic Superstar look onto this modern colorway. Mismatched leather eyelet panels combine with unique “SuperEarth” inspired branding on the left and right tongue tags to form a progressive look",
                            Name = "Superturf Adventure SW x A GW8810",
                            OriginalPrice = 2000000m,
                            Size = 42,
                            Stock = 0
                        });
                });

            modelBuilder.Entity("ShoesHouse.Data.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4501),
                            FileName = "1.1.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4750),
                            FileName = "1.2.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4753),
                            FileName = "1.3.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 4,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4755),
                            FileName = "1.4.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 5,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4756),
                            FileName = "2.1.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 6,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4758),
                            FileName = "2.2.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 7,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4760),
                            FileName = "2.3.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 8,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4761),
                            FileName = "2.4.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 9,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4764),
                            FileName = "3.1.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 10,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4766),
                            FileName = "3.2.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 11,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4767),
                            FileName = "3.3.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 12,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4769),
                            FileName = "3.4.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 13,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4771),
                            FileName = "4.1.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 14,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4772),
                            FileName = "4.2.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 15,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4774),
                            FileName = "4.3.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 16,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4775),
                            FileName = "4.4.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 17,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4777),
                            FileName = "5.1.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 18,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4779),
                            FileName = "5.2.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 19,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4780),
                            FileName = "5.3.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 20,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4782),
                            FileName = "5.4.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 21,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4783),
                            FileName = "6.1.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 22,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4785),
                            FileName = "6.2.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 23,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4787),
                            FileName = "6.3.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 24,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4788),
                            FileName = "6.4.jpg",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 25,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4790),
                            FileName = "7.1.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 26,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4791),
                            FileName = "7.2.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 27,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4793),
                            FileName = "7.3.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 28,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4795),
                            FileName = "7.4.jpg",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 29,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4796),
                            FileName = "8.1.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 30,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4798),
                            FileName = "8.2.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 31,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4800),
                            FileName = "8.3.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 32,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4801),
                            FileName = "8.4.jpg",
                            ProductId = 8
                        },
                        new
                        {
                            Id = 33,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4803),
                            FileName = "9.1.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 34,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4805),
                            FileName = "9.2.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 35,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4806),
                            FileName = "9.3.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 36,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4808),
                            FileName = "9.4.jpg",
                            ProductId = 9
                        },
                        new
                        {
                            Id = 37,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4809),
                            FileName = "10.1.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 38,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4811),
                            FileName = "10.2.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 39,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4813),
                            FileName = "10.3.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 40,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4814),
                            FileName = "10.4.jpg",
                            ProductId = 10
                        },
                        new
                        {
                            Id = 41,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4816),
                            FileName = "11.1.jpg",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 42,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4818),
                            FileName = "11.2.jpg",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 43,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4819),
                            FileName = "11.3.jpg",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 44,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4821),
                            FileName = "11.4.jpg",
                            ProductId = 11
                        },
                        new
                        {
                            Id = 45,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4822),
                            FileName = "12.1.jpg",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 46,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4824),
                            FileName = "12.2.jpg",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 47,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4826),
                            FileName = "12.3.jpg",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 48,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4837),
                            FileName = "12.4.jpg",
                            ProductId = 12
                        },
                        new
                        {
                            Id = 49,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4838),
                            FileName = "13.1.jpg",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 50,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4840),
                            FileName = "13.2.jpg",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 51,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4842),
                            FileName = "13.3.jpg",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 52,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4843),
                            FileName = "13.4.jpg",
                            ProductId = 13
                        },
                        new
                        {
                            Id = 53,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4845),
                            FileName = "14.1.jpg",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 54,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4847),
                            FileName = "14.2.jpg",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 55,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4848),
                            FileName = "14.3.jpg",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 56,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4850),
                            FileName = "14.4.jpg",
                            ProductId = 14
                        },
                        new
                        {
                            Id = 57,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4852),
                            FileName = "15.1.jpg",
                            ProductId = 15
                        },
                        new
                        {
                            Id = 58,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4853),
                            FileName = "15.2.jpg",
                            ProductId = 15
                        },
                        new
                        {
                            Id = 59,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4855),
                            FileName = "15.3.jpg",
                            ProductId = 15
                        },
                        new
                        {
                            Id = 60,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4856),
                            FileName = "15.4.jpg",
                            ProductId = 15
                        },
                        new
                        {
                            Id = 61,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4858),
                            FileName = "16.1.jpg",
                            ProductId = 16
                        },
                        new
                        {
                            Id = 62,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4860),
                            FileName = "16.2.jpg",
                            ProductId = 16
                        },
                        new
                        {
                            Id = 63,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4861),
                            FileName = "16.3.jpg",
                            ProductId = 16
                        },
                        new
                        {
                            Id = 64,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4863),
                            FileName = "16.4.jpg",
                            ProductId = 16
                        },
                        new
                        {
                            Id = 65,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4864),
                            FileName = "17.1.jpg",
                            ProductId = 17
                        },
                        new
                        {
                            Id = 66,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4866),
                            FileName = "17.2.jpg",
                            ProductId = 17
                        },
                        new
                        {
                            Id = 67,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4868),
                            FileName = "17.3.jpg",
                            ProductId = 17
                        },
                        new
                        {
                            Id = 68,
                            Caption = "Cake Image",
                            DateCreated = new DateTime(2022, 1, 27, 22, 51, 11, 829, DateTimeKind.Local).AddTicks(4869),
                            FileName = "17.4.jpg",
                            ProductId = 17
                        });
                });

            modelBuilder.Entity("ShoesHouse.Data.Entities.Cart", b =>
                {
                    b.HasOne("ShoesHouse.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShoesHouse.Data.Entities.AppUser", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShoesHouse.Data.Entities.Comment", b =>
                {
                    b.HasOne("ShoesHouse.Data.Entities.Product", "Product")
                        .WithMany("Comments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShoesHouse.Data.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShoesHouse.Data.Entities.Order", b =>
                {
                    b.HasOne("ShoesHouse.Data.Entities.AppUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShoesHouse.Data.Entities.OrderDetail", b =>
                {
                    b.HasOne("ShoesHouse.Data.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShoesHouse.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShoesHouse.Data.Entities.Product", b =>
                {
                    b.HasOne("ShoesHouse.Data.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ShoesHouse.Data.Entities.ProductImage", b =>
                {
                    b.HasOne("ShoesHouse.Data.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShoesHouse.Data.Entities.AppUser", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ShoesHouse.Data.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ShoesHouse.Data.Entities.Product", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ProductImages");
                });
#pragma warning restore 612, 618
        }
    }
}
